// Standard includes
#include "pebble.h"

#define TOTAL_IMAGE_SLOTS 6

#define NUMBER_OF_IMAGES 10

// Italian 0
// English 1
#define LANGUAGE 0

// These images are 38 x 62 pixels (i.e. a quarter of the display),
// black and white with the digit character centered in the image.
// (As generated by the `fonttools/font2png.py` script.)
const int IMAGE_RESOURCE_IDS[NUMBER_OF_IMAGES] = {
      RESOURCE_ID_IMAGE_NUM_0, RESOURCE_ID_IMAGE_NUM_1, RESOURCE_ID_IMAGE_NUM_2,
      RESOURCE_ID_IMAGE_NUM_3, RESOURCE_ID_IMAGE_NUM_4, RESOURCE_ID_IMAGE_NUM_5,
      RESOURCE_ID_IMAGE_NUM_6, RESOURCE_ID_IMAGE_NUM_7, RESOURCE_ID_IMAGE_NUM_8,
      RESOURCE_ID_IMAGE_NUM_9
};

const int SMALL_IMAGE_RESOURCE_IDS[NUMBER_OF_IMAGES] = {
      RESOURCE_ID_IMAGE_NUM_S_0, RESOURCE_ID_IMAGE_NUM_S_1, RESOURCE_ID_IMAGE_NUM_S_2,
      RESOURCE_ID_IMAGE_NUM_S_3, RESOURCE_ID_IMAGE_NUM_S_4, RESOURCE_ID_IMAGE_NUM_S_5,
      RESOURCE_ID_IMAGE_NUM_S_6, RESOURCE_ID_IMAGE_NUM_S_7, RESOURCE_ID_IMAGE_NUM_S_8,
      RESOURCE_ID_IMAGE_NUM_S_9
};

const int CONN_RESOURCE_IDS[2] = {
      RESOURCE_ID_CONN, RESOURCE_ID_DISC
};

const int BATT_RESOURCE_IDS[12] = {
      RESOURCE_ID_BATT_0, RESOURCE_ID_BATT_10, RESOURCE_ID_BATT_20, 
      RESOURCE_ID_BATT_30, RESOURCE_ID_BATT_40, RESOURCE_ID_BATT_50,
      RESOURCE_ID_BATT_60, RESOURCE_ID_BATT_70, RESOURCE_ID_BATT_80,
      RESOURCE_ID_BATT_90, RESOURCE_ID_BATT_100, RESOURCE_ID_BATT_CH  
};

#ifndef LANGUAGE
#define LANGUAGE 0
#endif

#if LANGUAGE == 0
#include "italian.h"
#elif LANGUAGE == 1 
#include "english.h"
#endif

static const int position[TOTAL_IMAGE_SLOTS][2][2] = {
  {{12,17},{38,62}},
  {{54,17},{38,62}},
  {{12,89},{38,62}},
  {{54,89},{38,62}},
  {{104,35},{12,20}},
  {{119,35},{12,20}}
};

static const int layers[4][2][2] = {
  {{100, 62}, {36, 120}},
  {{102, 134}, {12, 16}},
  {{122, 134}, {12, 16}},
  {{100, 16}, {36, 16}}
};

static TextLayer *ampm_layer;

#define EMPTY_SLOT -1

static GBitmap *slots[TOTAL_IMAGE_SLOTS] = {
  NULL, NULL, NULL, NULL, NULL, NULL 
};

static Layer *window_layer;
static BitmapLayer *digit_slot[TOTAL_IMAGE_SLOTS];
static GBitmap *battery_image;
static BitmapLayer *battery_layer;
static GBitmap *conn_image;
static BitmapLayer *conn_layer;
static TextLayer *date_layer;
static Window *window; 
static char date_text[24]    = "                        ";
  
static void do_deinit(void) {
  tick_timer_service_unsubscribe();
  battery_state_service_unsubscribe();
  bluetooth_connection_service_unsubscribe();
  
  for (int i = 0; i < TOTAL_IMAGE_SLOTS; i++) {
    gbitmap_destroy(slots[i]);
    bitmap_layer_destroy(digit_slot[i]);
  }
  gbitmap_destroy(conn_image);
  gbitmap_destroy(battery_image);
  text_layer_destroy(date_layer);
  bitmap_layer_destroy(conn_layer);
  bitmap_layer_destroy(battery_layer);
  text_layer_destroy(ampm_layer);
  window_destroy(window);
}

void load_icon_into_layer(int value, Layer* layer) {
  if ((int) layer == (int) conn_layer) {
    if (conn_image != NULL) {
      gbitmap_destroy(conn_image);
    }
    conn_image = gbitmap_create_with_resource(CONN_RESOURCE_IDS[value]);
    bitmap_layer_set_bitmap(conn_layer, conn_image);
    layer_mark_dirty(bitmap_layer_get_layer(conn_layer));
  } else if ((int) layer == (int) battery_layer) {
    if (battery_image != NULL) {
      gbitmap_destroy(battery_image);
    }
    battery_image = gbitmap_create_with_resource(BATT_RESOURCE_IDS[value]);
    bitmap_layer_set_bitmap(battery_layer, battery_image);
    layer_mark_dirty(bitmap_layer_get_layer(battery_layer));
  }
}

void load_digit_image_into_slot(int slot_number, int digit_value) {
  if (slots[slot_number] != NULL) {
    gbitmap_destroy(slots[slot_number]);
  }
  if (slot_number > 3) {
    slots[slot_number] = gbitmap_create_with_resource(SMALL_IMAGE_RESOURCE_IDS[digit_value]);
  } else {
    slots[slot_number] = gbitmap_create_with_resource(IMAGE_RESOURCE_IDS[digit_value]);
  };
  bitmap_layer_set_bitmap(digit_slot[slot_number], slots[slot_number]);
  layer_mark_dirty(bitmap_layer_get_layer(digit_slot[slot_number]));
}

void display_value(unsigned short value, unsigned short row_number, bool show_first_leading_zero) {
  value = value % 100; 
  
  for (int column_number = 1; column_number >= 0; column_number--) {
    int slot_number = (row_number * 2) + column_number;
    if (!((value == 0) && (column_number == 0) && !show_first_leading_zero)) {
      load_digit_image_into_slot(slot_number, value % 10);
    }
    value = value / 10;
  }
}

unsigned short get_display_hour(unsigned short hour) {
  if (clock_is_24h_style()) {
    return hour;
  }
  unsigned short display_hour = hour % 12;
  return display_hour ? display_hour : 12;
}

void update_date(struct tm *tick_time) {
#if LANGUAGE == 0
  snprintf(date_text, 24, "%s\n%02u\n%s\n%u", DOWS_SHORT[tick_time->tm_wday], tick_time->tm_mday, MONTHS[tick_time->tm_mon], (1900 + tick_time->tm_year));
#elif LANGUAGE == 1
  snprintf(date_text, 24, "%s,\n%s\n%02u\n%u", DOWS_SHORT[tick_time->tm_wday], MONTHS[tick_time->tm_mon], tick_time->tm_mday, (1900 + tick_time->tm_year));
#endif
}

static void handle_bluetooth(bool connected) {
  load_icon_into_layer(connected?0:1, bitmap_layer_get_layer(conn_layer));
}

static void handle_battery(BatteryChargeState charge_state) {
  static bool swc = true;
  int status = -1;
  if (charge_state.is_plugged) {
    if (charge_state.is_charging) {
      status = 11;
    } else {
        swc = !swc;
        status = swc?11:0;
    }
  } else {
    status = charge_state.charge_percent / 10;
  }
  if (status >= 0) {
    load_icon_into_layer(status, bitmap_layer_get_layer(battery_layer));
  }
}

static void handle_second_tick(struct tm* tick_time, TimeUnits units_changed) {
  static int day_m = 40;
  static int hour_m = 33;
  static int min_m = 77;
  static bool clock24 = false;
  
  if (clock24 != clock_is_24h_style()) {
    clock24 = clock_is_24h_style();
    for (int slot_number = 4; slot_number < TOTAL_IMAGE_SLOTS; slot_number++) {
      GRect bounds = layer_get_frame(bitmap_layer_get_layer(digit_slot[slot_number]));
      if (clock24) {
        bounds.origin.y = 19;
      } else {
        bounds.origin.y = 35;
      }
      layer_set_frame(bitmap_layer_get_layer(digit_slot[slot_number]), bounds);
    }
    GRect bounds = layer_get_frame(text_layer_get_layer(date_layer));
    if (clock24) {
      bounds.origin.y = 52;
    } else {
      bounds.origin.y = 62;
    }
    layer_set_frame(text_layer_get_layer(date_layer), bounds);
    layer_set_hidden((Layer *)ampm_layer, clock24);
  }
  
  if (day_m != tick_time->tm_mday) {
    day_m = tick_time->tm_mday;
    update_date(tick_time);
    text_layer_set_text(date_layer, date_text);
  }
  if (hour_m != tick_time->tm_hour) {
    hour_m = tick_time->tm_hour;
    display_value(get_display_hour(tick_time->tm_hour), 0, true);
    if (!clock_is_24h_style()) {
      if (hour_m >=12) {
        text_layer_set_text(ampm_layer, "PM");
      } else {
        text_layer_set_text(ampm_layer, "AM");
      }
    }
  }
    
  if (min_m != tick_time->tm_min) {
    min_m = tick_time->tm_min;
    display_value(tick_time->tm_min, 1, true);  
  }
  display_value(tick_time->tm_sec, 2, true);
}

static void do_init(void) {
  window = window_create();

  window_stack_push(window, true);
  window_layer = window_get_root_layer(window);
  
  date_layer = text_layer_create(GRect(layers[0][0][0],layers[0][0][1],layers[0][1][0],layers[0][1][1]));
  text_layer_set_text_alignment(date_layer, GTextAlignmentCenter);
  text_layer_set_text(date_layer, "");
  
  ampm_layer = text_layer_create(GRect(layers[3][0][0],layers[3][0][1],layers[3][1][0],layers[3][1][1]));
  text_layer_set_text_alignment(ampm_layer, GTextAlignmentCenter);
  text_layer_set_text(ampm_layer, "");
  text_layer_set_text_color(date_layer, GColorBlack);
  text_layer_set_background_color(date_layer, GColorWhite);
  text_layer_set_font(date_layer, fonts_load_custom_font(resource_get_handle(RESOURCE_ID_ROBOTO_BOLD_16)));
  
  conn_layer = bitmap_layer_create(
    GRect(layers[1][0][0],layers[1][0][1],layers[1][1][0],layers[1][1][1]));
  load_icon_into_layer(0, bitmap_layer_get_layer(conn_layer));
  
  battery_layer = bitmap_layer_create(
    GRect(layers[2][0][0],layers[2][0][1],layers[2][1][0],layers[2][1][1]));
  load_icon_into_layer(0, bitmap_layer_get_layer(battery_layer));
  
  int adj = 0;
  for (int slot_number = 0; slot_number < TOTAL_IMAGE_SLOTS; slot_number++) {
    digit_slot[slot_number] = bitmap_layer_create(
        GRect(position[slot_number][0][0], position[slot_number][0][1], position[slot_number][1][0], position[slot_number][1][1]));
    
    load_digit_image_into_slot(slot_number, slot_number);
    layer_add_child(window_layer, bitmap_layer_get_layer(digit_slot[slot_number]));
  }
  
    time_t now = time(NULL);
  struct tm *current_time = localtime(&now);
  
  handle_second_tick(current_time, SECOND_UNIT);
  handle_bluetooth(bluetooth_connection_service_peek());
  handle_battery(battery_state_service_peek());
  
  tick_timer_service_subscribe(SECOND_UNIT, &handle_second_tick);
  battery_state_service_subscribe(&handle_battery);
  bluetooth_connection_service_subscribe(&handle_bluetooth);
  
  layer_add_child(window_layer, text_layer_get_layer(date_layer));
  
  window_set_background_color(window, GColorWhite);
  text_layer_set_text_color(date_layer, GColorBlack);
  text_layer_set_background_color(date_layer, GColorWhite);
  text_layer_set_font(date_layer, fonts_load_custom_font(resource_get_handle(RESOURCE_ID_ROBOTO_BOLD_16)));

  layer_add_child(window_layer, bitmap_layer_get_layer(conn_layer));
  layer_add_child(window_layer, bitmap_layer_get_layer(battery_layer));
  
  layer_add_child(window_layer, text_layer_get_layer(ampm_layer));
}

int main(void) {
  do_init();
  app_event_loop();
  do_deinit();
}
